python3 tests/movie/test_movie.py \
    --cast_info $(kip cast_info) \
    --compose_review $(kip compose_review) \
    --frontend $(kip frontend) \
    --movie_id $(kip movie_id) \
    --movie_info $(kip movie_info) \
    --movie_reviews $(kip movie_reviews) \
    --page $(kip page) \
    --plot $(kip plot) \
    --review_storage $(kip review_storage) \
    --unique_id $(kip unique_id) \
    --user $(kip user) \
    --user_reviews $(kip user_reviews)
